### ISSUE TITLE
bsseq object and h5 file

### ISSUE THREAD

**Issue by eddiehli** [hansenlab/bsseq#100]
Hello I encountered the problem with HDF5 matrix type bsseq objects. Specifically, when I tried to use getCoverage, I encountered the following problem. Thank you in advance for your help. 

```r
> library(bsseq)
> library(SummarizedExperiment)
> library(Biobase)
> library(DelayedArray)
> library(matrixStats)
> library(HDF5Array)
> 
> load("./data/combined_ptsd_bs_chr024_CpG.rda")
> 
> BS_big@assays$data$M@seed@seed@filepath = "/Users/hongyuli/Documents/WBGS/data/combined_ptsd_assays_chr024.h5"
> BS_big@assays$data$Cov@seed@filepath = "/Users/hongyuli/Documents/WBGS/data/combined_ptsd_assays_chr024.h5"
> 
> h5ls("/Users/hongyuli/Documents/WBGS/data/combined_ptsd_assays_chr024.h5")
  group       name       otype  dclass             dim
0     /    Cov_CpG H5I_DATASET INTEGER   451824 x 1301
1     / Cov_nonCpG H5I_DATASET INTEGER 10120859 x 1301
2     /      M_CpG H5I_DATASET INTEGER   451824 x 1301
3     /   M_nonCpG H5I_DATASET INTEGER 10120859 x 1301
> 
> head(getCoverage(BS_big, type = "M"), n = 4)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'head': 'assay(<BSseq>, i="character", ...)' invalid subscript 'i'
invalid class “DelayedMatrix” object: superclass "DataTable_OR_NULL" not defined in the environment of the object's class
```

**Comment by PeteHaitch** [comment]
It's hard to provide help without having access to the specific dataset. Is it something you can share?

Nonetheless, a few things stand out to me:

- This *BSseq* object doesn't appear to have been saved ('serialized') using the officially support `HDF5Array::saveHDF5SummarizedExperiment()`. If it had, there would be a directory containing a `.rds` file and a `.h5` file that you would load with `HDF5Array::loadHDF5SummarizedExperiment()`.
-  Instead, you are trying to `load()` an `.rda` version of the *BSseq* object. **Saving a HDF5-backed *BSseq* object with `save()` and then trying to load it with `load()` will generally not work**. It certainly won't work if any of the files have been moved e.g., you're working on a different computer (see `?HDF5Array::saveHDF5SummarizedExperiment` for details).

Minor thing: if you want to know the path to the HDF5 file backing an assay, use `path(assay(BS, "M"))` rather than direct slot access (`BS@assays$data$M@seed@seed@filepath`).

If you generated the original *BSseq* object then I strongly recommend you re-save it using `HDF5Array::saveHDF5SummarizedExperiment()`.
If you only have access to the `.rda` and `.h5` files, there may still be a way to construct a valid *BSseq* object.
It'll be something like the following pseudocode (I obviously can't test this without access to the data):

```r
M <- HDF5Matrix(filepath = "/Users/hongyuli/Documents/WBGS/data/combined_ptsd_assays_chr024.h5", name = "M_Cpg")
Cov <- HDF5Matrix(filepath = "/Users/hongyuli/Documents/WBGS/data/combined_ptsd_assays_chr024.h5", name = "Cov_Cpg")
load("./data/combined_ptsd_bs_chr024_CpG.rda")
gr <- rowRanges(BS_big)
pd <- colData(BS_big)
bsseq <- BSseq(M = M, Cov = Cov, gr = gr, pData = pd)
```

Again, once you have created the *BSseq* object, I would strongly recommend running `HDF5Array::saveHDF5SummarizedExperiment(bsseq)` and using that for subsequent analysis because that version will be fully portable (e.g., moving directories or working on different computers).

**Comment by eddiehli** [comment]
Thank you for your reply!
